name: SCCore
authors: [Anml, superckl]
version: 1.0
main: com.sensationcraft.sccore.SCCore
depend: [Essentials, Factions, ProtocolLib]
commands:
  channel:
    aliases: [c]
  staff:
    aliases: [st]
  rank:
    default: false
  perms:
    default: false
  arena:
    default: false
  duel:
  spectate:
  ban:
    default: false
  tempban:
    default: false
  mute:
    default: false
  tempmute:
    default: false
  unban:
    default: false
  unmute:
    default: false
  kick:
    default: false
  warn:
    default: false
  history:
    default: false
  helprequest:
      aliases: [hr]
  shop:
    default: false
  givekeyshard:
  tutorial:
      aliases: [tut]
  help:
      aliases: [?]
